{% set name = "hockey_rink" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hockey_rink-{{ version }}.tar.gz
  sha256: e2628546ded69bc810180661f1b7bacdb741adfef44de3ba1cac7fe073fd537a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pillow

test:
  imports:
    - hockey_rink
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/the-bucketless/hockey_rink
  summary: A Python library for plotting hockey rinks with Matplotlib.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
